name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set ruby version
      run: RUBY_VERSION=$(~/.rbenv/plugins/rbenv-bundler-ruby-version/bin/rbenv-bundler-ruby-version) && rbenv install -s $RUBY_VERSION
    - name: Install bundler
      run: gem install bundler
    - name: Pod install
      run: bundle exec pod install
    - name: Build and test
      run: bundle exec fastlane ci_check
    - name: Pod lib lint
      run: pod lib lint
